apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: products-db
spec:
  serviceName: "products-db"
  replicas: 2
  selector:
    matchLabels:
      app: products-db
  template:
    metadata:
      labels:
        app: products-db
    spec:
      containers:
        - name: postgres
          image: widgetario/products-db:postgres-replicated
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: SuperSecret123
            - name: REPLICATION_PASSWORD
              value: SuperSecret123
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi