apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: products-db
spec:
  serviceName: products-db
  replicas: 2
  selector:
    matchLabels:
      app: products-db
  template:
    metadata:
      labels:
        app: products-db
    spec:
      containers:
      - name: postgres
        image: widgetario/products-db:postgres-replicated
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: securepassword
        - name: POSTGRES_REPLICATION_PASSWORD
          value: securepassword
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

